name: Greetings

on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: say-hello
      run : echo "hello world"
